repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: requirements-txt-fixer
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: no-commit-to-branch
        args:
          - --branch=master
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        name: black
        args:
          - --safe
          - --quiet
        files: ^(pyesef|tests)/.+\.py$
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        files: ^(pyesef|tests)/.+\.py$
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        args:
          - --timeout=30
          - --cov=pyesef
          - --cov-report=html
        stages: [push, manual]
        entry: pytest
        language: system
        types: [python]
        files: tests
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        files: ^(pyesef|tests)/.+\.py$
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: ./script/run-pre-commit.sh mypy
        language: script
        types: [python]
        require_serial: true
        files: ^(pyesef|tests)/.+\.py$
