repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.275
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: requirements-txt-fixer
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: no-commit-to-branch
        args:
          - --branch=main
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: black
        args:
          - --safe
          - --quiet
        files: ^(pyesef|tests)/.+\.py$
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        files: ^(pyesef|tests)/.+\.py$
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: ./script/run-pre-commit.sh mypy
        language: script
        types: [python]
        require_serial: true
        files: ^(pyesef|tests)/.+\.py$
