[build-system]
requires = ["setuptools==69.1.1", "wheel~=0.42.0", "toml"]
build-backend = "setuptools.build_meta"

[project]
name        = "pyesef"
version     = "1.0.2"
license     = {text = "MIT"}
description = "Parse financial statements in XBRL format"
authors     = [
    {name = "ggravlingen", email = "no@email.com"}
]
keywords    = ["esef", "statement", "financial"]
requires-python = ">=3.10.0"
dependencies    = [
  "arelle-release==2.23.13",
  "ipykernel==6.29.3",
  "jstyleson==0.0.2",
  "lxml==4.9.3,<5",
  "pandas==2.2.1",
  "requests==2.31.0",
]
classifiers=[
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Intended Audience :: Financial and Insurance Industry",
]

[tool.setuptools]
platforms = ["any"]
zip-safe  = false
include-package-data = true
packages = ["pyesef"]

[tool.setuptools.package-data]
"pyesef" = ["py.typed"]

[tool.black]
target-version = ["py310"]

[tool.pylint.MASTER]
py-version = "3.10"

[tool.pylint.BASIC]
class-const-naming-style = "any"

[tool.pylint."MESSAGES CONTROL"]
disable = [
  "broad-except",
  "too-many-instance-attributes",
  "too-many-return-statements",
  "too-few-public-methods",
  "too-many-locals",
]

[tool.pylint.REPORTS]
score = false

[tool.pylint.FORMAT]
expected-line-ending-format = "LF"

[tool.pylint.EXCEPTIONS]
overgeneral-exceptions = [
    "BaseException",
    "Exception",
]

[tool.pylint.TYPING]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
norecursedirs = [
    ".git",
    "testing_config",
]

[tool.ruff]
exclude = []

target-version = "py310"

select = [
    "B007", # Loop control variable {name} not used within loop body
    "B014", # Exception handler with duplicate exception
    "C",  # complexity
    "D",  # docstrings
    "E",  # pycodestyle
    "F",  # pyflakes/autoflake
    "I",  # isort
    "ICN001", # import concentions; {name} should be imported as {asname}
    "PGH004",  # Use specific rule codes when using noqa
    "PLC0414", # Useless import alias. Import alias does not rename original package.
    "T20",  # flake8-print
    "UP",  # pyupgrade
    "W",  # pycodestyle
]

# Same as Black.
line-length = 88

ignore = [# One of these is to be disabled..
          "D213", # See https://github.com/charliermarsh/ruff/issues/2281
          #"D212", # See https://github.com/charliermarsh/ruff/issues/2281

          "D203", # See https://github.com/charliermarsh/ruff/issues/2281
          #"D211", # See https://github.com/charliermarsh/ruff/issues/2281
              # keep-runtime-annotations
          'UP006', # Non PEP585 annotations
          'UP007', # Non PEP604 annotations
]

[tool.ruff.flake8-pytest-style]
fixture-parentheses = false

[tool.ruff.pydocstyle]
convention = 'pep257'

[tool.ruff.isort]
combine-as-imports = true
force-sort-within-sections = true
forced-separate = [
  "tests",
]
known-first-party = [
  "pyesef",
  "tests",
]
