ARG VARIANT=3.10-bullseye
FROM mcr.microsoft.com/vscode/devcontainers/python:${VARIANT}

ENV FILE_LOCATION "/usr/src/app"

WORKDIR $FILE_LOCATION

RUN python3 -m pip install --upgrade pip setuptools wheel Cython tox
