#!/bin/sh
# Resolve all dependencies that the application requires to run.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

echo "Installing dependencies..."

. $VIRTUAL_ENV/bin/activate \
    && python3 -m pip install -r requirements_test.txt \
    && python3 -m pip install -e .
